### ISSUE TITLE
pyHICCUPS　error?

### ISSUE THREAD

**Issue by liufuyan2016** [XiaoTaoWang/HiCPeaks#1]
Dear,
when I use example provided for call loops, command below:
python ../scripts/pyHICCUPS -O K562-MboI-HICCUPS-loops.txt -p K562-MboI-parts.cool::40000 --pw 1 --ww 3
An error occured:

root           INFO    @ 09/03/18 13:59:59: Loading Hi-C data ...
root           INFO    @ 09/03/18 13:59:59: Calling Peaks ...
root           INFO    @ 09/03/18 13:59:59: Chromosome 21 ...
Traceback (most recent call last):
  File "../scripts/pyHICCUPS", line 522, in <module>
    run()
  File "../scripts/pyHICCUPS", line 181, in run
    results = map_(worker, Params)
  File "../scripts/pyHICCUPS", line 130, in worker
    Diags = [H.diagonal(i) for i in np.arange(num)]
TypeError: diagonal() takes exactly 1 argument (2 given)

Could you help me?

**Comment by liufuyan2016** [comment]
Could you help me? Thanks you!
